settings:
  legacy:
    force: false
    interval: 0s
schema:
  - name: evm-tennis
    path: .
    commands:
      install:
        method: go build -o tennis
        status: true
      run:
        method: ./tennis
        status: true
    watcher:
      extensions:
        - go
      paths:
        - /
      ignored_paths:
        - .git
        - .realize
        - vendor
